# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-02-03 15:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0014_select'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booklist',
        ),
        migrations.DeleteModel(
            name='Penlist',
        ),
        migrations.DeleteModel(
            name='Select',
        ),
    ]
