# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-02-03 15:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0015_auto_20200203_2101'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
